const SEND_MESS = "SEND_MESS";
const RECEIVE_MESS = "RECEIVE_MESS";

const SEND_TYPING = "SEND_TYPING";
const RECEIVE_TYPING = "RECEIVE_TYPING";

const SEND_READ_ALL_MESS = "SEND_READ_ALL_MESS";
const RECEIVE_READ_ALL_MESS = "RECEIVE_READ_ALL_MESS";

module.exports = {
  SEND_MESS,
  RECEIVE_MESS,
  SEND_TYPING,
  RECEIVE_TYPING,
  SEND_READ_ALL_MESS,
  RECEIVE_READ_ALL_MESS,
};
