const SEND_MESS = "SEND_MESS";
const RECEIVE_MESS = "RECEIVE_MESS";

const SEND_TYPING = "SEND_TYPING";
const RECEIVE_TYPING = "RECEIVE_TYPING";

module.exports = { SEND_MESS, RECEIVE_MESS, SEND_TYPING, RECEIVE_TYPING };
